// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServiceAuto.Web.Data;

#nullable disable

namespace ServiceAuto.Web.Migrations
{
    [DbContext(typeof(ServiceAutoContext))]
    [Migration("20260111121805_FixDecimalPrecision")]
    partial class FixDecimalPrecision
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ServiceAuto.Web.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipClient")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("ServiceAuto.Web.Models.Interventie", b =>
                {
                    b.Property<int>("InterventieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InterventieId"));

                    b.Property<DateTime>("DataProgramare")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriereProblema")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MasinaId")
                        .HasColumnType("int");

                    b.Property<int>("MecanicId")
                        .HasColumnType("int");

                    b.Property<string>("ObservatiiMecanic")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("InterventieId");

                    b.HasIndex("MasinaId");

                    b.HasIndex("MecanicId");

                    b.ToTable("Interventii");
                });

            modelBuilder.Entity("ServiceAuto.Web.Models.InterventiePiesa", b =>
                {
                    b.Property<int>("InterventieId")
                        .HasColumnType("int");

                    b.Property<int>("PiesaDeSchimbId")
                        .HasColumnType("int");

                    b.Property<int>("Cantitate")
                        .HasColumnType("int");

                    b.Property<decimal>("PretUnitarLaDataAplicarii")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("InterventieId", "PiesaDeSchimbId");

                    b.HasIndex("PiesaDeSchimbId");

                    b.ToTable("InterventiiPiese");
                });

            modelBuilder.Entity("ServiceAuto.Web.Models.Masina", b =>
                {
                    b.Property<int>("MasinaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MasinaId"));

                    b.Property<int>("AnFabricatie")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumarInmatriculare")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("SerieSasiu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MasinaId");

                    b.HasIndex("ClientId");

                    b.ToTable("Masini");
                });

            modelBuilder.Entity("ServiceAuto.Web.Models.Mecanic", b =>
                {
                    b.Property<int>("MecanicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MecanicId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ParolaHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Prenume")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MecanicId");

                    b.ToTable("Mecanici");
                });

            modelBuilder.Entity("ServiceAuto.Web.Models.PiesaDeSchimb", b =>
                {
                    b.Property<int>("PiesaDeSchimbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PiesaDeSchimbId"));

                    b.Property<string>("CodProdus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Furnizor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Pret")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stoc")
                        .HasColumnType("int");

                    b.HasKey("PiesaDeSchimbId");

                    b.ToTable("PieseDeSchimb");
                });

            modelBuilder.Entity("ServiceAuto.Web.Models.Interventie", b =>
                {
                    b.HasOne("ServiceAuto.Web.Models.Masina", "Masina")
                        .WithMany()
                        .HasForeignKey("MasinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceAuto.Web.Models.Mecanic", "Mecanic")
                        .WithMany("Interventii")
                        .HasForeignKey("MecanicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Masina");

                    b.Navigation("Mecanic");
                });

            modelBuilder.Entity("ServiceAuto.Web.Models.InterventiePiesa", b =>
                {
                    b.HasOne("ServiceAuto.Web.Models.Interventie", "Interventie")
                        .WithMany("InterventiiPiese")
                        .HasForeignKey("InterventieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceAuto.Web.Models.PiesaDeSchimb", "PiesaDeSchimb")
                        .WithMany("InterventiiPiese")
                        .HasForeignKey("PiesaDeSchimbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interventie");

                    b.Navigation("PiesaDeSchimb");
                });

            modelBuilder.Entity("ServiceAuto.Web.Models.Masina", b =>
                {
                    b.HasOne("ServiceAuto.Web.Models.Client", "Client")
                        .WithMany("Masini")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("ServiceAuto.Web.Models.Client", b =>
                {
                    b.Navigation("Masini");
                });

            modelBuilder.Entity("ServiceAuto.Web.Models.Interventie", b =>
                {
                    b.Navigation("InterventiiPiese");
                });

            modelBuilder.Entity("ServiceAuto.Web.Models.Mecanic", b =>
                {
                    b.Navigation("Interventii");
                });

            modelBuilder.Entity("ServiceAuto.Web.Models.PiesaDeSchimb", b =>
                {
                    b.Navigation("InterventiiPiese");
                });
#pragma warning restore 612, 618
        }
    }
}
